### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-1-Samoylenko** [UMSF-K13-1-Samoylenko/K13---1---Samoylenko--MainProject#1]
Я создал папку K13-1-Samoylenko Svyatoslav-MainProject, в ней создал файл K13-1-Samoylenko Svyatoslav-MainProject.txt с текстом K13-1-Samoylenko Svyatoslav-MainProject. С помощью Git Bush выполнил следующие команды: 
git init
git add .
git commit -m "first commit"
git remote add origin https://github.com/UMSF-K13-1-Samoylenko/K13---1---Samoylenko--MainProject.git
![other](https://cloud.githubusercontent.com/assets/19637421/15720201/ffe1262a-283b-11e6-89e2-e86785991b20.png)
![45324](https://cloud.githubusercontent.com/assets/19637421/15720202/ffe183e0-283b-11e6-9efc-9d293c413cfb.png)

**Comment by Smoktii** [comment]
Ок
